// THIS FILE IS AUTO GENERATED!
// DO NOT EDIT IT!!!

#include <string>

inline std::string buildin_samfile_content = R"(
_build_in_copy_links_md:
    MV .samengine/links.md pages/links.md
_build_in_minisite_build_bun:
    ECHO Info This Task has changed because linksaver moved to l2. See more here: https://shadowdara.github.io/docs/#/linksaver
    SHELL l2 view
    TASK _build_in_copy_links_md
    SHELL bun x sam-cli minisite
_build_in_minisite_build_npm:
    ECHO Info This Task has changed because linksaver moved to l2. See more here: https://shadowdara.github.io/docs/#/linksaver
    SHELL l2 view
    TASK _build_in_copy_links_md
    SHELL npx sam-cli minisite
_build_in_gitignore_godot:
    APPEND .gitignore '# Ignore autogenerated Files image from the 3D Models'
    APPEND .gitignore "models/*.png"
    APPEND .gitignore "models/*.png.import"
    APPEND .gitignore "models/*.jpg"
    APPEND .gitignore "models/*.jpg.import"
    APPEND .gitignore "models/*.jpeg"
    APPEND .gitignore "models/*.jpeg.import"
    ECHO Ignored all images files form 3D Models by Godot
_build_in_gitignore_samengine:
    APPEND .gitignore '# Ignore autogenerated files from samengine'
    APPEND .gitignore .samengine/config.mjs
    APPEND .gitignore dist
    APPEND .gitignore .samengine/links.md
    APPEND .gitignore .samengine/links.txt
    APPEND .gitignore pages/links.md
    ECHO Ignore autogenerated files from samengine
_build_in_docs:
    RUNLIN curl -# -o shadowdara_docs.html "https://raw.githubusercontent.com/shadowdara/docs/refs/heads/main/docs/index.html"
    RUNMAC curl -# -o shadowdara_docs.html "https://raw.githubusercontent.com/shadowdara/docs/refs/heads/main/docs/index.html"
    RUNWIN curl.exe -# -o shadowdara_docs.html "https://raw.githubusercontent.com/shadowdara/docs/refs/heads/main/docs/index.html"
    ECHO pulled the Docs from Github with curl
_build_in_init:
    TOUCH samfile
    APPEND samfile '# This is a new samfile'
    APPEND samfile '#'
    APPEND samfile '# Visit the Link to gain more Infos about samfiles'
    APPEND samfile '# https://shadowdara.github.io/docs/#/samfile'
    APPEND samfile '#'
_build_in_samfile_lang:
    APPEND .gitattributes '# mark samfile as shell'
    APPEND .gitattributes "samfile linguist-language=Shell"
_build_in_cmake:
    RUN cmake -S . -B build
    RUN cmake --build build
_build_in_cmake_r:
    RUN cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
    RUN cmake --build build
_build_in_docs_wget:
    RUN wget -O shadowdara_docs.html https://raw.githubusercontent.com/shadowdara/docs/refs/heads/main/docs/index.html
    ECHO pulled the Docs from Github with wget
_build_in_samfile:
    RUN git clone https://gist.github.com/efa77c93aa83301c20b759bfae496d85.git
_bclm:
    TASK _build_in_copy_links_md
_bcm:
    TASK _build_in_cmake
_bcmr:
    TASK _build_in_cmake_r
_bd:
    TASK _build_in_docs
)";
