// THIS FILE IS AUTO GENERATED!
// DO NOT EDIT IT!!!

#include <string>

inline std::string buildin_samfile_content = R"(
_build_in_copy_links_md:
    MV .samengine/links.md pages/links.md
_build_in_minisite_build_bun:
    SHELL bun x seg -l view
    TASK _build_in_copy_links_md
    SHELL bun x sam-cli minisite
_build_in_minisite_build_npm:
    SHELL npx seg -l view
    TASK _build_in_copy_links_md
    SHELL npx sam-cli minisite
_build_in_gitignore_godot:
    APPEND .gitignore '# Ignore autogenerated Files image from the 3D Models'
    APPEND .gitignore "models/*.png"
    APPEND .gitignore "models/*.png.import"
    APPEND .gitignore "models/*.jpg"
    APPEND .gitignore "models/*.jpg.import"
    APPEND .gitignore "models/*.jpeg"
    APPEND .gitignore "models/*.jpeg.import"
    ECHO Ignored all images files form 3D Models by Godot
_build_in_gitignore_samengine:
    APPEND .gitignore '# Ignore autogenerated files from samengine'
    APPEND .gitignore .samengine/config.mjs
    APPEND .gitignore dist
    APPEND .gitignore .samengine/links.md
    APPEND .gitignore .samengine/links.txt
    APPEND .gitignore pages/links.md
    ECHO Ignore autogenerated files from samengine
_build_in_docs:
    RUN curl https://raw.githubusercontent.com/shadowdara/docs/refs/heads/main/docs/index.html
    ECHO pulled the Docs from Github with curl
_build_in_docs_wget:
    RUN wget https://raw.githubusercontent.com/shadowdara/docs/refs/heads/main/docs/index.html
    ECHO pulled the Docs from Github with wget
_build_in_init:
    TOUCH samfile
    APPEND samfile "# This is a new samfile"
    APPEND samfile "#"
    APPEND samfile "# Visit the Link to gain more Infos about samfiles"
    APPEND samfile "# https://shadowdara.github.io/docs/#/samfile"
    APPEND samfile "#"
_build_in_samfile_lang:
    APPEND .gitattributes "# mark samfile as shell"
    APPEND .gitattributes "samfile linguist-language=Shell"
)";
